# Errors and Exceptions
a=5 
print(a)